# Generated by Django 3.1.1 on 2021-09-03 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='BillType',
            field=models.CharField(blank=True, choices=[('GST Bill', 'GST Bill'), ('TDS Bill', 'TDS Bill'), ('Cash', 'Cash')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='CompanyName',
            field=models.ForeignKey(blank=True, help_text='If expenses towrds that particular company', null=True, on_delete=django.db.models.deletion.CASCADE, to='p1.customerdetails'),
        ),
    ]
