# Generated by Django 3.1.1 on 2021-09-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0002_auto_20210903_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='IsWithTax',
            field=models.BooleanField(default=False, help_text='Tick if tax included'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='Tax',
            field=models.FloatField(blank=True, help_text='18/12/5/10/1/0.75/0/any other tax', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='IsWithTax',
            field=models.BooleanField(default=False, help_text='Tick if tax included'),
        ),
    ]
