# Generated by Django 3.1.1 on 2021-09-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0003_auto_20210903_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingdetails',
            old_name='BillNo',
            new_name='Bill_No',
        ),
        migrations.RenameField(
            model_name='billingdetails',
            old_name='BillType',
            new_name='Bill_Type',
        ),
        migrations.RenameField(
            model_name='billingdetails',
            old_name='BillValue',
            new_name='Bill_Value',
        ),
        migrations.RenameField(
            model_name='billingdetails',
            old_name='CompanyName',
            new_name='Company_Name',
        ),
        migrations.RenameField(
            model_name='billingdetails',
            old_name='IsWithTax',
            new_name='Is_With_Tax',
        ),
        migrations.RenameField(
            model_name='contactdetails',
            old_name='CompanyName',
            new_name='Company_Name',
        ),
        migrations.RenameField(
            model_name='contactdetails',
            old_name='OtherInfo',
            new_name='Other_Info',
        ),
        migrations.RenameField(
            model_name='contactdetails',
            old_name='PersonName',
            new_name='Person_Name',
        ),
        migrations.RenameField(
            model_name='contactdetails',
            old_name='PhoneNumber',
            new_name='Phone_Number',
        ),
        migrations.RenameField(
            model_name='customerdetails',
            old_name='NickName',
            new_name='Nick_Name',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='CompanyName',
            new_name='Company_Name',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='OrderDetails',
            new_name='Order_Details',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='OrderValue',
            new_name='Order_Value',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='BillNo',
            new_name='Bill_No',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='CompanyName',
            new_name='Company_Name',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='IsCleared',
            new_name='Is_Cleared',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='PaidValue',
            new_name='Paid_Value',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='PaymentDate',
            new_name='Payment_Date',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='BillDate',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='NextDate',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='IsWithTax',
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='Bill_Date',
            field=models.DateField(blank=True, help_text='Purchase Date', null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='Next_Date',
            field=models.DateField(help_text='next commitment date if available', null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='Is_With_Tax',
            field=models.BooleanField(default=False, help_text='tick if tax included'),
        ),
    ]
