# Generated by Django 3.1.1 on 2021-09-07 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0005_auto_20210904_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='Name',
            field=models.CharField(help_text='Company Name', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Order_RefName',
            field=models.ForeignKey(help_text='PO reference person name', on_delete=django.db.models.deletion.CASCADE, to='p1.contactdetails'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='Next_Date',
            field=models.DateField(blank=True, help_text='next commitment date if available', null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='PO_Copy',
            field=models.ImageField(blank=True, help_text='Attach Purchase Order', null=True, upload_to='images'),
        ),
    ]
