# Generated by Django 3.1.1 on 2021-09-09 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0009_auto_20210908_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='Bill_No',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='p1.billingdetails'),
        ),
    ]
