# Generated by Django 3.2.8 on 2021-10-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0010_auto_20210909_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='Attatch',
            field=models.FileField(blank=True, upload_to='expenses/'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='Date',
            field=models.DateField(help_text='yyyy-mm-dd', null=True),
        ),
    ]
