# Generated by Django 3.2.8 on 2021-10-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0011_auto_20211025_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='Attatch',
        ),
    ]
