# Generated by Django 3.2.8 on 2021-10-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0012_remove_expenses_attatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='Attach',
            field=models.FileField(blank=True, upload_to='expenses/'),
        ),
    ]
